server:
  port: 8080

spring:
  liquibase:
    url: ${DB_URL_JDBC:jdbc:postgresql://postgresql:5432/shop}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:myPassword}
  r2dbc:
    url: ${DB_URL_R2DBC:r2dbc:postgresql://postgresql:5432/shop}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:myPassword}

jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3FQ09N1aRw2sJeEwBR3BqTFsYGt8dz3QUwz
    dDJkWSXloR94zUQbdKz6SS99OCpAUul0090VoOWD1akEsh3Xkx8g39tY2YclwZPAqxf7RsxBRbuW5nB
    QcpriTPPQr1D+myqllr3UlZ8I2W1pqBGo4rpkapndIb4acqTZjn8VVQ52twYyowNvBtV5xWccwTwoV/
    A5GrewvAO/qyDadOPkZSPJt6xxbV35zNhLPGDdg4aI7YaIDJWmr2zHrgDpZj7684XKYLi22hV7px9yO
    KUg03R/170q4SbjkKLO4xIJ5wwwzbqxza/7gA8gjF6spdCW7NAxphf0M7zGGX8oTTqdbsQIDAQAB
    -----END PUBLIC KEY-----
  private-key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDcVDT03VpHDawl4TAFHcGpMWxga3x3PdBTDN0MmRZ
    JeWhH3jNRBt0rPpJL304KkBS6XTT3RWg5YPVqQSyHdeTHyDf21jZhyXBk8CrF/tGzEFFu5bmcFBymuJM89CvUP6bKqW
    WvdSVnwjZbWmoEajiumRqmd0hvhpypNmOfxVVDna3BjKjA28G1XnFZxzBPChX8Dkat7C8A7+rINp04+RlI8m3rHFtXf
    nM2Es8YN2DhojthogMlaavbMeuAOlmPvrzhcpguLbaFXunH3I4pSDTdH/XvSrhJuOQos7jEgnnDDDNurHNr/uADyCMX
    qyl0Jbs0DGmF/QzvMYZfyhNOp1uxAgMBAAECggEAAOqGt9ftxqrbYuLvUK4hfoMamMIJp/NFWPsONj2ytoZ/NQFLBFS
    7ebEOaatZhzi3JVk63aZXuxlYm+L+fOe0FlKSTP/yBPER+xF2lBEtrQlt1UC2R1xcDCNrVU8MmZrUJjaTGioqCCbqE/
    Ipy6/nYW54imWnkvMj1p5HxsPKyXet5cyl13HVmx1OTDKV3O2rE1nWLiQkAJg3hnEGOmXTW9m0c06MH6OldNcF6oyWQ
    7dibLSvsz7eJxt6ndP9NNtACl8XqyHDctpJ7ozghX+NENnKHGxzugDajnZWEjSDYjI8nGF8t+ZgEW0Sf0MKXZO1ViOK
    TseIWW3xJJiaQqKgewKBgQDkk8VUbOvlHwHLPy96RfQLkhmk7leIpqgalNlHglJjyARE2fd+0XibhUGniYVoKzAZY1d
    3VrsAojGpFvgL8BeRxUpVzq7UPQBTgA0slZph5wIVaBWKcqIeUmpBMilLd56n9x7lIES1bp92ct8xfypnwPnsuhUWkz
    LsgSh8UwyLAwKBgQD2wxu/VpcJQl0zfN/94/LOvaYolIjFmm1HXKdkWSAgb32dE/bkzaMcSI6uxS4nZnPhFiSWNIx5d
    IhE8OkF5p9HpiGlRjHF/XXOVDPVt09ZZRuQeYbFIitibaOfdZ2tZK4UC+TU3FCCI1qJkfjxRTw6spnRhDAt0o+tj/Td
    sBXGOwKBgQCR3I524o7iBhhh9683ar5iR9gffIzVQexSEhxZWpty2yeGPEWIYumA7NdJryM3px+pg9BD8k+hBt+D1Il
    zLMINnoViHmNIQqkbn8JIais7QGv+9w2P7LjxeowdkIHzi6Dt9G99rUrLMI2Hy6QL9Oc9kFKsMs7UOhir/Xu1YlXFuw
    KBgQDEmv9om50LC40mkMAGka/LeN8CRhYTGs8mpHPaSAiIz0vN8zIraowi5MyKAyCa085P8EyGQKgLvQU1qJyAzxbpB
    zyXai4OCbvrALur87mNCDnGCo2OU4MtkR1k11kh5a2s2y0fS8n5ZiGkqmEmGnu6aMKVZDTezX0cVC5M0xcGMQKBgQDM
    M0Uf+FZ2oJPQuG1SJDRK5bLUerAxtLqicJJFCZHaQSPD8fneYGihwebdUyz7cpwBUcu7fE0pcBU81CZGl+2jcyNMq9F
    18byJBIYGAnZaTZi9XhzZqbHouas7lnl3Fuv5NFTblZH2SRrQoHLiG+365XeKE0FkTb/KPqVI6uQpqQ==
    -----END RSA PRIVATE KEY-----
